About TensorFlow and Deep Learning:-

**TensorFlow:** A Python library that is used for modelling/implementation of deep learning models/networks. TensorFlow = Tensors + Flow. Tensor corresponds to the way data is represented in this library and Flow depicts the flow of these Tensors through the <i>computation graph</i>.

A <i>computation graph</i> is series of TensorFlow operations arranged into a graph of nodes.

**Tensors**: The standard way of representing data in TensorFlow. Tensors are nothing but multidimensional arrays, an extension of matrices (2D tables) to data with higher dimensions.

Note: Only tensors may be passed between nodes in a computation graph.

<ul>

<li> Dimensionality is measured as **Ranks**:-

<ol>
    
   <li> Rank 0 -> a Scalar, example: s = 482

   <li> Rank 1 -> a Vector, example: v = [1, 2, 3]

   <li> Rank 2 -> a Matrix, example: m = [[1,5,6], [2,5,6], [3,5,6]]

   <li> Rank 3 -> a 3-Tesor or a cube holding some data, example: t = [[[1,5,6], [2,5,6], [3,5,6]], [[1,5,6], [2,5,6], [3,5,6]], [[1,5,6], [2,5,6], [3,5,6]]]
    
</ol>

    ...

   ** Rank n -> n-Tensor **

<li> Tensor Data Types:- 

Tensorflow automattically assigns the correct data type. If you want to specifically assign the data type in order to save memory or do some other operation, it is possible.

<ol>
  
   <li> DT_FLOAT -> tf.float32
    
   <li> DT_DOUBLE-> tf.float64
    
   <li> DT_INT8 -> tf.int8

   <li> DT_UINT8 -> tf.uint8
    
   ...
    
   <li> DT_INT64 -> tf.int64
    
   <li> DT_STRING -> tf.string
    
   <li> DT_BOOL -> tf.bool
    
</ol>
    

**TensorFlow Coding structure**

It consists of two sections in particular:-

<ul>
    <li> Building a computation graph.
    <li> Running the computation graph.
        

**1** - Building a graph

In [1]:
# Import the TensorFlow library
import tensorflow as tf
import numpy as np

# Defining two constant nodes
aNode = tf.constant(5.0)
bNode = tf.constant(1.9, tf.float32)

cNode = aNode*bNode;

# At this point, they are just abstract Tensors and not actual calculations are running.
# Only operations are created.
print (aNode, bNode, cNode)

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Tensor("Const:0", shape=(), dtype=float32) Tensor("Const_1:0", shape=(), dtype=float32) Tensor("mul:0", shape=(), dtype=float32)


**2** - Running a graph

In [2]:
# To execute the graph, we run it inside a session
# A session places graph operations onto devices such as CPU/GPU.

''' Method 1 '''

aSession = tf.Session()

print (aSession.run([aNode, bNode]))
# You need to close a session in order to free up the resources it used.
aSession.close()

''' Method 2 '''

with tf.Session() as bSession:
    # You just need to run the output Tensor
    output = bSession.run(cNode)
    print (output)
bSession.close()

[5.0, 1.9]
9.5


**Visualizing TensorFlow: TensorBoard**

TensorBoard is a suite of web-applications for understanding your Tensor graphs.

The most convinient way to do this is using FileWriter by:     

In [3]:
aNode = tf.constant(5.0)
bNode = tf.constant(1.9, tf.float32)
cNode = aNode*bNode;

with tf.Session() as bSession:
    output = bSession.run(cNode)    
    # Give the first argument as a path and the second as the graph of the session
    aFileWriter = tf.summary.FileWriter('aSimpleGraph', aSession.graph)
bSession.close()

After writing the log, go to the directory in your command line and type:

   ** tensorboad --logdir="TensorFlow" **
   
It will say that the TensorBoard runs at http://localhost:6006/



You have been seeing constant nodes in the previous examples. Let us dig deeper into them and other nodes in TensorFlow

**1. Constants**: As the name suggests, they have hardcoded values and take in no inputs. All they do is output this internal value in an active session.

**2. Placeholders**: These nodes are able to take in external input, assuming that they will be provided one at runtime.

In [4]:
aNode = tf.placeholder(tf.float32)
bNode = tf.placeholder(tf.float32)

summedNode = aNode + bNode;
# You can also use the in-build TensorFlow operations
# summedNode = tf.add(aNode, bNode);

xNode = tf.placeholder(tf.float32, shape=(1024, 1024))
# matmul is the in-built TensorFlow operation for matrix-multiplication
yNode = tf.matmul(xNode, xNode)

with tf.Session() as aSession:
    # ERROR: will fail because placeholder was not fed.
    #output = aSession.run(summedNode);
    #output = aSession.run(summedNode);

    # This will succeed.
    randArrayA = np.random.rand(1, 2)
    randArrayB = np.random.rand(1, 2)
    output = aSession.run(summedNode, feed_dict={aNode: randArrayA, bNode: randArrayB});
    print ("A: ",randArrayA, "\nB: ", randArrayB, "\nA+B: ",output)
    
    randArrayX = np.random.rand(1024, 1024)
    print("\nX:", randArrayX, "\nX*X:", aSession.run(yNode, feed_dict={xNode: randArrayX}))  # Will succeed.
aSession.close()

A:  [[0.23313773 0.2844311 ]] 
B:  [[0.10211448 0.8355557 ]] 
A+B:  [[0.33525223 1.1199868 ]]

X: [[0.76313563 0.9065525  0.32440845 ... 0.49741626 0.50019583 0.11704756]
 [0.37421243 0.38296898 0.25924542 ... 0.86231968 0.40420137 0.71002387]
 [0.13893258 0.46083097 0.82178146 ... 0.86745065 0.29185133 0.53283617]
 ...
 [0.27915509 0.69321072 0.56813464 ... 0.16981308 0.9930976  0.0525749 ]
 [0.34943331 0.44936957 0.39633732 ... 0.09998226 0.67308295 0.97709263]
 [0.0202177  0.40685868 0.4393103  ... 0.13153815 0.48851592 0.57090187]] 
X*X: [[254.31223 261.9021  259.7486  ... 262.18668 258.52127 261.90085]
 [250.84096 260.94064 259.23694 ... 263.15625 258.04282 264.0538 ]
 [255.56479 265.75198 265.67847 ... 267.9383  256.8534  264.97784]
 ...
 [246.74905 255.22658 251.13799 ... 253.10086 250.78667 254.35167]
 [252.78789 258.29706 255.91455 ... 265.49756 259.21896 263.75568]
 [246.37346 258.87375 258.57007 ... 260.93933 256.1042  256.2373 ]]


<br>
**3. Variables**: Used to integrate trainable parameters to the graph. The weights and the offset are the best examples of variables. Here is an example of variable usage in training a model:-

In [5]:
# Model parameters
W = tf.Variable([.30], tf.float32)
b = tf.Variable([-.30], tf.float32)

# input and output variables
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

linearModel = W*x + b

# Loss (this will tell us how far we are from getting to the right answer)
squaredDelta = tf.square(linearModel - y)
loss = tf.reduce_sum(squaredDelta)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

# Initialize all the variables
init = tf.global_variables_initializer()

'''
An Optimizer modifies each variable according to the magnitude of the derivate of the
loss with respect to that variable. Gradient Descent is a type of Optimizer.

Gradient Descent:-

Suppose there is a Hiker are on the top of a mountain in a mountain range. The Hiker is blindfolded and
he wants to reach the ground. He starts moving in the direction that takes him lower until it starts
going up again.

Hence, the Position of hiker is weight. Length of the step is the learning rate.

OR in other words:

An Optimizer will calculate the change in the loss WRT to change in the variable. If the loss is 
decreasing then it will continue changing the varibale in that direction.
'''

with tf.Session() as someSession:
    someSession.run(init)

    for i in range(1000):
        someSession.run(train, {x:[1,2,3,4], y:[0,-1,-2,-3]})
    print (someSession.run([W, b]))
someSession.close()

[array([-0.9999969], dtype=float32), array([0.9999908], dtype=float32)]


**Creating a classifier using what we have learned/used so far**

Problem: (Binary Classificatoin) Given some training data with n features and corresponding labels (0 or 1), train a binary classifier and predict the labels on the test set.

In [46]:
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

def readData():
    # Read the training data and separate the dependent variable from the features
    trainDataFrame = pd.read_csv("sonar.csv")
    nCols = len(trainDataFrame.columns)
    X = trainDataFrame[trainDataFrame.columns[0:nCols-1]].values
    y = trainDataFrame[trainDataFrame.columns[nCols-1]].values
    
    # Encoding the dependent variable
    # Incase of labels such as "Yes" and "No", we want to map them to a corresponding label vector
    # that has all zeroes expect at the corresponding label.
    encoder = LabelEncoder()
    encoder.fit(y)
    y = encoder.transform(y)
    Y = one_hot_encode(y)
    
    return (X, Y)
    
def one_hot_encode(labels):
    nLabels = len(labels)
    nUniqueLabels = len(np.unique(labels))
    one_hot_encode = np.zeros((nLabels, nUniqueLabels))
    one_hot_encode[np.arange(nLabels), labels] = 1
    return one_hot_encode
    
    
X, Y = readData()
X, Y = shuffle(X, Y, random_state=1)

# print (Y)

# Dividing the training data into train and dev sets
train_x, test_x, train_y, test_y = train_test_split(X, Y, test_size = 0.2, )#random_state = 415)

# print (train_y)

# Inspect the shape after dividing into the right data sets
# print ((train_x.shape))
# print ((test_x.shape))
# print ((train_y.shape))
# print ((test_y.shape))

# Important parameters and modelling variables
learning_rate = 0.25
training_epochs = 100
cost_history = np.empty(shape=[1], dtype=float)

# dimension of the feature vector
n_dim = X.shape[1]
print ("Number of features: ", n_dim)
# Number of possible labels / output classes
n_class = Y.shape[1]
print ("Number of labels: ", n_class)

# Define the number of hidden layers and Neurons in each layer
n_hidden_1 = 40
n_hidden_2 = 30
n_hidden_3 = 40
n_hidden_4 = 40

# input and output variables
x = tf.placeholder(tf.float32, [None, n_dim]) # 'None' tells that it can be any value
W = tf.Variable(tf.zeros([n_dim,n_class]))
b = tf.Variable(tf.zeros([n_class]))
y_ = tf.placeholder(tf.float32, [None, n_class]) # 'None' tells that it can be any value

# Defining the model
def multiLayerPerceptron(x, weights, biases):
    
    layer_1 = tf.add(tf.matmul(x, weights["h1"]), biases["b1"])
    layer_1 = tf.nn.sigmoid(layer_1)
    
    layer_2 = tf.add(tf.matmul(layer_1, weights["h2"]), biases["b2"])
    layer_2 = tf.nn.sigmoid(layer_2)

    layer_3 = tf.add(tf.matmul(layer_2, weights["h3"]), biases["b3"])
    layer_3 = tf.nn.sigmoid(layer_3)

    layer_4 = tf.add(tf.matmul(layer_3, weights["h4"]), biases["b4"])
    layer_4 = tf.nn.relu(layer_4)
    
    layer_out = tf.matmul(layer_4, weights["out"]) + biases["out"]
    
    return layer_out

weights = {
    'h1': tf.Variable(tf.truncated_normal([n_dim, n_hidden_1])),
    'h2': tf.Variable(tf.truncated_normal([n_hidden_1, n_hidden_2])),
    'h3': tf.Variable(tf.truncated_normal([n_hidden_2, n_hidden_3])),
    "h4": tf.Variable(tf.truncated_normal([n_hidden_3, n_hidden_4])),
    "out": tf.Variable(tf.truncated_normal([n_hidden_4, n_class]))
}

biases = {
    'b1': tf.Variable(tf.truncated_normal([n_hidden_1])),
    'b2': tf.Variable(tf.truncated_normal([n_hidden_2])),
    'b3': tf.Variable(tf.truncated_normal([n_hidden_3])),
    "b4": tf.Variable(tf.truncated_normal([n_hidden_4])),
    "out": tf.Variable(tf.truncated_normal([n_class]))
}


# Initialize all the variables
init = tf.global_variables_initializer()

saver = tf.train.Saver()

y = multiLayerPerceptron(x, weights, biases)

costFunction = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=y,labels=y_))
trainingStep = tf.train.GradientDescentOptimizer(learning_rate).minimize(costFunction)

optimizer = tf.train.GradientDescentOptimizer(0.01)

mseHistory = []
accHistory = []

someSession = tf.Session()
someSession.run(init)

for epoch in range(training_epochs):
    someSession.run(trainingStep, feed_dict={x: train_x, y_: train_y})
    cost = someSession.run(trainingStep, {x: train_x, y_: train_y})
    cost_history = np.append(cost_history, cost)
    correctPred = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
    acc = tf.reduce_mean(tf.cast(correctPred, tf.float32))

    pred_y = someSession.run(y, {x: test_x})
    mse = tf.reduce_mean(tf.square(pred_y - test_y))
    mse_ = someSession.run(mse)
    mseHistory.append(mse_)
    acc = (someSession.run(acc, {x: train_x, y_: train_y}))
    accHistory.append(acc)

    print ("\nepoch: ", epoch, " Acc: ", acc)
        
# save_path = saver.save(someSession, )
someSession.close()

print (mseHistory)
print (accHistory)

Number of features:  60
Number of labels:  2

epoch:  0  Acc:  0.54545456

epoch:  1  Acc:  0.54545456

epoch:  2  Acc:  0.58181816

epoch:  3  Acc:  0.56969696

epoch:  4  Acc:  0.58787876

epoch:  5  Acc:  0.6121212

epoch:  6  Acc:  0.6121212

epoch:  7  Acc:  0.6363636

epoch:  8  Acc:  0.6363636

epoch:  9  Acc:  0.6484848

epoch:  10  Acc:  0.6606061

epoch:  11  Acc:  0.6848485

epoch:  12  Acc:  0.6484848

epoch:  13  Acc:  0.6060606

epoch:  14  Acc:  0.6242424

epoch:  15  Acc:  0.6121212

epoch:  16  Acc:  0.6363636

epoch:  17  Acc:  0.53939396

epoch:  18  Acc:  0.56969696

epoch:  19  Acc:  0.53939396

epoch:  20  Acc:  0.6

epoch:  21  Acc:  0.58787876

epoch:  22  Acc:  0.6363636

epoch:  23  Acc:  0.58787876

epoch:  24  Acc:  0.6484848

epoch:  25  Acc:  0.58787876

epoch:  26  Acc:  0.5939394

epoch:  27  Acc:  0.6

epoch:  28  Acc:  0.58181816

epoch:  29  Acc:  0.6

epoch:  30  Acc:  0.58787876

epoch:  31  Acc:  0.58181816

epoch:  32  Acc:  0.58181816

epoch:  33