About TensorFlow and Deep Learning:-

**TensorFlow:** A Python library that is used for modelling/implementation of deep learning models/networks. TensorFlow = Tensors + Flow. Tensor corresponds to the way data is represented in this library and Flow depicts the flow of these Tensors through the <i>computation graph</i>.

A <i>computation graph</i> is series of TensorFlow operations arranged into a graph of nodes.

**Tensors**: The standard way of representing data in TensorFlow. Tensors are nothing but multidimensional arrays, an extension of matrices (2D tables) to data with higher dimensions.

Note: Only tensors may be passed between nodes in a computation graph.

<ul>

<li> Dimensionality is measured as **Ranks**:-

<ol>
    
   <li> Rank 0 -> a Scalar, example: s = 482

   <li> Rank 1 -> a Vector, example: v = [1, 2, 3]

   <li> Rank 2 -> a Matrix, example: m = [[1,5,6], [2,5,6], [3,5,6]]

   <li> Rank 3 -> a 3-Tesor or a cube holding some data, example: t = [[[1,5,6], [2,5,6], [3,5,6]], [[1,5,6], [2,5,6], [3,5,6]], [[1,5,6], [2,5,6], [3,5,6]]]
    
</ol>

    ...

   ** Rank n -> n-Tensor **

<li> Tensor Data Types:- 

Tensorflow automattically assigns the correct data type. If you want to specifically assign the data type in order to save memory or do some other operation, it is possible.

<ol>
  
   <li> DT_FLOAT -> tf.float32
    
   <li> DT_DOUBLE-> tf.float64
    
   <li> DT_INT8 -> tf.int8

   <li> DT_UINT8 -> tf.uint8
    
   ...
    
   <li> DT_INT64 -> tf.int64
    
   <li> DT_STRING -> tf.string
    
   <li> DT_BOOL -> tf.bool
    
</ol>
    

**TensorFlow Coding structure**

It consists of two sections in particular:-

<ul>
    <li> Building a computation graph.
    <li> Running the computation graph.
        

**1** - Building a graph

In [1]:
# Import the TensorFlow library
import tensorflow as tf
import numpy as np

# Defining two constant nodes
aNode = tf.constant(5.0)
bNode = tf.constant(1.9, tf.float32)

cNode = aNode*bNode;

# At this point, they are just abstract Tensors and not actual calculations are running.
# Only operations are created.
print (aNode, bNode, cNode)

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Tensor("Const:0", shape=(), dtype=float32) Tensor("Const_1:0", shape=(), dtype=float32) Tensor("mul:0", shape=(), dtype=float32)


**2** - Running a graph

In [2]:
# To execute the graph, we run it inside a session
# A session places graph operations onto devices such as CPU/GPU.

''' Method 1 '''

aSession = tf.Session()

print (aSession.run([aNode, bNode]))
# You need to close a session in order to free up the resources it used.
aSession.close()

''' Method 2 '''

with tf.Session() as bSession:
    # You just need to run the output Tensor
    output = bSession.run(cNode)
    print (output)
bSession.close()

[5.0, 1.9]
9.5


**Visualizing TensorFlow: TensorBoard**

TensorBoard is a suite of web-applications for understanding your Tensor graphs.

The most convinient way to do this is using FileWriter by:     

In [3]:
aNode = tf.constant(5.0)
bNode = tf.constant(1.9, tf.float32)
cNode = aNode*bNode;

with tf.Session() as bSession:
    output = bSession.run(cNode)    
    # Give the first argument as a path and the second as the graph of the session
    aFileWriter = tf.summary.FileWriter('aSimpleGraph', aSession.graph)
bSession.close()

After writing the log, go to the directory in your command line and type:

   ** tensorboad --logdir="TensorFlow" **
   
It will say that the TensorBoard runs at http://localhost:6006/



You have been seeing constant nodes in the previous examples. Let us dig deeper into them and other nodes in TensorFlow

**1. Constants**: As the name suggests, they have hardcoded values and take in no inputs. All they do is output this internal value in an active session.

**2. Placeholders**: These nodes are able to take in external input, assuming that they will be provided one at runtime.

In [4]:
aNode = tf.placeholder(tf.float32)
bNode = tf.placeholder(tf.float32)

summedNode = aNode + bNode;
# You can also use the in-build TensorFlow operations
# summedNode = tf.add(aNode, bNode);

xNode = tf.placeholder(tf.float32, shape=(1024, 1024))
# matmul is the in-built TensorFlow operation for matrix-multiplication
yNode = tf.matmul(xNode, xNode)

with tf.Session() as aSession:
    # ERROR: will fail because placeholder was not fed.
    #output = aSession.run(summedNode);
    #output = aSession.run(summedNode);

    # This will succeed.
    randArrayA = np.random.rand(1, 2)
    randArrayB = np.random.rand(1, 2)
    output = aSession.run(summedNode, feed_dict={aNode: randArrayA, bNode: randArrayB});
    print ("A: ",randArrayA, "\nB: ", randArrayB, "\nA+B: ",output)
    
    randArrayX = np.random.rand(1024, 1024)
    print("\nX:", randArrayX, "\nX*X:", aSession.run(yNode, feed_dict={xNode: randArrayX}))  # Will succeed.
aSession.close()

A:  [[0.09628455 0.04013548]] 
B:  [[0.9588434 0.2384872]] 
A+B:  [[1.055128  0.2786227]]

X: [[0.17665679 0.92436702 0.03543605 ... 0.22319722 0.97795651 0.16782616]
 [0.37308356 0.27207303 0.44560627 ... 0.04632262 0.70691266 0.66263241]
 [0.19653761 0.20654682 0.39907982 ... 0.59950445 0.16686145 0.29342747]
 ...
 [0.56601218 0.09143504 0.61979671 ... 0.48119927 0.10804474 0.74068156]
 [0.70787955 0.5259055  0.43678699 ... 0.02699478 0.95645921 0.28866577]
 [0.19381777 0.24777248 0.73393277 ... 0.5931318  0.57560468 0.51895267]] 
X*X: [[261.33505 257.94604 257.83853 ... 256.2542  266.19772 263.08475]
 [260.25317 255.72462 256.71622 ... 253.58792 262.6249  254.52263]
 [269.83893 264.357   264.67615 ... 261.75647 271.45398 262.81573]
 ...
 [268.61176 263.1862  267.73013 ... 263.42484 268.1549  258.25046]
 [254.83615 245.73447 245.3367  ... 243.03151 246.2926  242.38742]
 [264.4721  251.63567 254.13    ... 259.0703  254.8607  252.34216]]


<br>
**3. Variables**: Used to integrate trainable parameters to the graph. The weights and the offset are the best examples of variables. Here is an example of variable usage in training a model:-

In [5]:
# Model parameters
W = tf.Variable([.30], tf.float32)
b = tf.Variable([-.30], tf.float32)

# input and output variables
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

linearModel = W*x + b

# Loss (this will tell us how far we are from getting to the right answer)
squaredDelta = tf.square(linearModel - y)
loss = tf.reduce_sum(squaredDelta)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

# Initialize all the variables
init = tf.global_variables_initializer()

'''
An Optimizer modifies each variable according to the magnitude of the derivate of the
loss with respect to that variable. Gradient Descent is a type of Optimizer.

Gradient Descent:-

Suppose there is a Hiker are on the top of a mountain in a mountain range. The Hiker is blindfolded and
he wants to reach the ground. He starts moving in the direction that takes him lower until it starts
going up again.

Hence, the Position of hiker is weight. Length of the step is the learning rate.

OR in other words:

An Optimizer will calculate the change in the loss WRT to change in the variable. If the loss is 
decreasing then it will continue changing the varibale in that direction.
'''

with tf.Session() as someSession:
    someSession.run(init)

    for i in range(1000):
        someSession.run(train, {x:[1,2,3,4], y:[0,-1,-2,-3]})
    print (someSession.run([W, b]))
someSession.close()

[array([-0.9999969], dtype=float32), array([0.9999908], dtype=float32)]


**Creating a classifier using what we have learned/used so far**

Problem: (Binary Classificatoin) Given some training data with n features and corresponding labels (0 or 1), train a binary classifier and predict the labels on the test set.

In [1]:
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

def readData():
    # Read the training data and separate the dependent variable from the features
    trainDataFrame = pd.read_csv("final_processed_2.csv")
    
    # df.columns is zero-based pd.Index
    X = trainDataFrame.drop(['div','FTR', 'key', 'date', 'WHH','WHD','WHA'], axis=1)
    y = trainDataFrame['FTR']
    
#     nCols = len(trainDataFrame.columns)
    
#     X = trainDataFrame[trainDataFrame.columns[0:nCols-1]].values
#     y = trainDataFrame[trainDataFrame.columns[nCols-1]].values
    
    # Encoding the dependent variable
    # Incase of labels such as "Yes" and "No", we want to map them to a corresponding label vector
    # that has all zeroes expect at the corresponding label.
    encoder = LabelEncoder()
    encoder.fit(y)
    y = encoder.transform(y)
    Y = one_hot_encode(y)
    

    display(X.head())
    
    return (X, Y)
    
def one_hot_encode(labels):
    nLabels = len(labels)
    nUniqueLabels = len(np.unique(labels))
    one_hot_encode = np.zeros((nLabels, nUniqueLabels))
    one_hot_encode[np.arange(nLabels), labels] = 1
    return one_hot_encode
    
    
X, Y = readData()
X, Y = shuffle(X, Y, random_state=1)

# print (Y)

# Dividing the training data into train and dev sets
train_x, test_x, train_y, test_y = train_test_split(X, Y, test_size = 0.2, )#random_state = 415)

# print (train_y)

# Inspect the shape after dividing into the right data sets
# print ((train_x.shape))
# print ((test_x.shape))
# print ((train_y.shape))
# print ((test_y.shape))

# Important parameters and modelling variables
learning_rate = 0.1
training_epochs = 1000
cost_history = np.empty(shape=[1], dtype=float)

# dimension of the feature vector
n_dim = X.shape[1]
print ("Number of features: ", n_dim)
# Number of possible labels / output classes
n_class = Y.shape[1]
print ("Number of labels: ", n_class)

# Define the number of hidden layers and Neurons in each layer
n_hidden_1 = 40
n_hidden_2 = 30
n_hidden_3 = 40
n_hidden_4 = 40

# input and output variables
x = tf.placeholder(tf.float32, [None, n_dim]) # 'None' tells that it can be any value
W = tf.Variable(tf.zeros([n_dim,n_class]))
b = tf.Variable(tf.zeros([n_class]))
y_ = tf.placeholder(tf.float32, [None, n_class]) # 'None' tells that it can be any value

# Defining the model
def multiLayerPerceptron(x, weights, biases):
    
    layer_1 = tf.add(tf.matmul(x, weights["h1"]), biases["b1"])
    layer_1 = tf.nn.sigmoid(layer_1)
    
    layer_2 = tf.add(tf.matmul(layer_1, weights["h2"]), biases["b2"])
    layer_2 = tf.nn.sigmoid(layer_2)

    layer_3 = tf.add(tf.matmul(layer_2, weights["h3"]), biases["b3"])
    layer_3 = tf.nn.sigmoid(layer_3)

    layer_4 = tf.add(tf.matmul(layer_3, weights["h4"]), biases["b4"])
    layer_4 = tf.nn.relu(layer_4)
    
    layer_out = tf.matmul(layer_4, weights["out"]) + biases["out"]
    
    return layer_out

weights = {
    'h1': tf.Variable(tf.truncated_normal([n_dim, n_hidden_1])),
    'h2': tf.Variable(tf.truncated_normal([n_hidden_1, n_hidden_2])),
    'h3': tf.Variable(tf.truncated_normal([n_hidden_2, n_hidden_3])),
    "h4": tf.Variable(tf.truncated_normal([n_hidden_3, n_hidden_4])),
    "out": tf.Variable(tf.truncated_normal([n_hidden_4, n_class]))
}

biases = {
    'b1': tf.Variable(tf.truncated_normal([n_hidden_1])),
    'b2': tf.Variable(tf.truncated_normal([n_hidden_2])),
    'b3': tf.Variable(tf.truncated_normal([n_hidden_3])),
    "b4": tf.Variable(tf.truncated_normal([n_hidden_4])),
    "out": tf.Variable(tf.truncated_normal([n_class]))
}


# Initialize all the variables
init = tf.global_variables_initializer()

saver = tf.train.Saver()

y = multiLayerPerceptron(x, weights, biases)

costFunction = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=y,labels=y_))
trainingStep = tf.train.GradientDescentOptimizer(learning_rate).minimize(costFunction)

# optimizer = tf.train.GradientDescentOptimizer(0.01)

mseHistory = []
accHistory = []

someSession = tf.Session()
someSession.run(init)

for epoch in range(training_epochs):
    someSession.run(trainingStep, feed_dict={x: train_x, y_: train_y})
    cost = someSession.run(trainingStep, {x: train_x, y_: train_y})
    cost_history = np.append(cost_history, cost)
    correctPred = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
    acc = tf.reduce_mean(tf.cast(correctPred, tf.float32))

    pred_y = someSession.run(y, {x: test_x})
    mse = tf.reduce_mean(tf.square(pred_y - test_y))
    mse_ = someSession.run(mse)
    mseHistory.append(mse_)
    acc = (someSession.run(acc, {x: train_x, y_: train_y}))
    accHistory.append(acc)

    if (epoch % 100 == 1):
        print ("\nepoch: ", epoch, " Acc: ", acc)
        
# save_path = saver.save(someSession, )
someSession.close()

print (mseHistory)
print (accHistory)

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


team1  team2  team1_home_win  team1_home_draw  team1_away_win  \
0      4      7        0.472222         0.277778        0.147059   
1      9     19        0.277778         0.444444        0.117647   
2      4      3        0.447368         0.302632        0.171053   
3     24      6        0.000000         0.500000        0.500000   
4     20     16        0.393939         0.318182        0.230769   

   team1_away_draw  team1_home_goals  team1_away_goals  \
0         0.323529          1.250000          0.735294   
1         0.117647          0.888889          0.529412   
2         0.250000          1.342105          0.684211   
3         0.000000          1.500000          1.500000   
4         0.276923          1.590909          1.015385   

   team1_home_goals_conceded  team1_away_goals_conceded        ...          \
0                   0.944444                   1.647059        ...           
1                   1.055556                   1.882353        ...           
2                   0.973684                   1.710526        ...           
3                   2.000000                   2.500000        ...           
4                   1.287879                   1.661538        ...           

   away_player_4  away_player_5  away_player_6  away_player_7  away_player_8  \
0             65             69             61             72             58   
1             76             69             60             62             67   
2             56             68             70             59             58   
3             76             64             73             68             81   
4             55             58             78             80             67   

   away_player_9  away_player_10  away_player_11  home_team_overall  \
0             71              72              59                429   
1             81              69              76                395   
2             73              61              63                429   
3             57              69              65                459   
4             75              60              77                430   

   away_team_overall  
0                431  
1                420  
2                467  
3                501  
4                370  

[5 rows x 109 columns]

Number of features:  109
Number of labels:  3
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.


epoch:  1  Acc:  0.2890625


KeyboardInterrupt: 