About TensorFlow and Deep Learning:-

**TensorFlow:** A Python library that is used for modelling/implementation of deep learning models/networks. TensorFlow = Tensors + Flow. Tensor corresponds to the way data is represented in this library and Flow depicts the flow of these Tensors through the <i>computation graph</i>.

A <i>computation graph</i> is series of TensorFlow operations arranged into a graph of nodes.

**Tensors**: The standard way of representing data in TensorFlow. Tensors are nothing but multidimensional arrays, an extension of matrices (2D tables) to data with higher dimensions.

Note: Only tensors may be passed between nodes in a computation graph.

<ul>

<li> Dimensionality is measured as **Ranks**:-

<ol>
    
   <li> Rank 0 -> a Scalar, example: s = 482

   <li> Rank 1 -> a Vector, example: v = [1, 2, 3]

   <li> Rank 2 -> a Matrix, example: m = [[1,5,6], [2,5,6], [3,5,6]]

   <li> Rank 3 -> a 3-Tesor or a cube holding some data, example: t = [[[1,5,6], [2,5,6], [3,5,6]], [[1,5,6], [2,5,6], [3,5,6]], [[1,5,6], [2,5,6], [3,5,6]]]
    
</ol>

    ...

   ** Rank n -> n-Tensor **

<li> Tensor Data Types:- 

Tensorflow automattically assigns the correct data type. If you want to specifically assign the data type in order to save memory or do some other operation, it is possible.

<ol>
  
   <li> DT_FLOAT -> tf.float32
    
   <li> DT_DOUBLE-> tf.float64
    
   <li> DT_INT8 -> tf.int8

   <li> DT_UINT8 -> tf.uint8
    
   ...
    
   <li> DT_INT64 -> tf.int64
    
   <li> DT_STRING -> tf.string
    
   <li> DT_BOOL -> tf.bool
    
</ol>
    

**TensorFlow Coding structure**

It consists of two sections in particular:-

<ul>
    <li> Building a computation graph.
    <li> Running the computation graph.
        

**1** - Building a graph

In [27]:
# Import the TensorFlow library
import tensorflow as tf
import numpy as np

# Defining two constant nodes
aNode = tf.constant(5.0)
bNode = tf.constant(1.9, tf.float32)

cNode = aNode*bNode;

# At this point, they are just abstract Tensors and not actual calculations are running.
# Only operations are created.
print (aNode, bNode, cNode)

Tensor("Const_10:0", shape=(), dtype=float32) Tensor("Const_11:0", shape=(), dtype=float32) Tensor("mul_5:0", shape=(), dtype=float32)


**2** - Running a graph

In [28]:
# To execute the graph, we run it inside a session
# A session places graph operations onto devices such as CPU/GPU.

''' Method 1 '''

aSession = tf.Session()

print (aSession.run([aNode, bNode]))
# You need to close a session in order to free up the resources it used.
aSession.close()

''' Method 2 '''

with tf.Session() as bSession:
    # You just need to run the output Tensor
    output = bSession.run(cNode)
    print (output)
bSession.close()

[5.0, 1.9]
9.5


**Visualizing TensorFlow: TensorBoard**

TensorBoard is a suite of web-applications for understanding your Tensor graphs.

The most convinient way to do this is using FileWriter by:     

In [29]:
aNode = tf.constant(5.0)
bNode = tf.constant(1.9, tf.float32)
cNode = aNode*bNode;

with tf.Session() as bSession:
    output = bSession.run(cNode)    
    # Give the first argument as a path and the second as the graph of the session
    aFileWriter = tf.summary.FileWriter('aSimpleGraph', aSession.graph)
bSession.close()

After writing the log, go to the directory in your command line and type:

   ** tensorboad --logdir="TensorFlow" **
   
It will say that the TensorBoard runs at http://localhost:6006/



You have been seeing constant nodes in the previous examples. Let us dig deeper into them and other nodes in TensorFlow

**1. Constants**: As the name suggests, they have hardcoded values and take in no inputs. All they do is output this internal value in an active session.

**2. Placeholders**: These nodes are able to take in external input, assuming that they will be provided one at runtime.

In [52]:
aNode = tf.placeholder(tf.float32)
bNode = tf.placeholder(tf.float32)

summedNode = aNode + bNode;
# You can also use the in-build TensorFlow operations
# summedNode = tf.add(aNode, bNode);

xNode = tf.placeholder(tf.float32, shape=(1024, 1024))
# matmul is the in-built TensorFlow operation for matrix-multiplication
yNode = tf.matmul(xNode, xNode)

with tf.Session() as aSession:
    # ERROR: will fail because placeholder was not fed.
    #output = aSession.run(summedNode);
    #output = aSession.run(summedNode);

    # This will succeed.
    randArrayA = np.random.rand(1, 2)
    randArrayB = np.random.rand(1, 2)
    output = aSession.run(summedNode, feed_dict={aNode: randArrayA, bNode: randArrayB});
    print ("A: ",randArrayA, "\nB: ", randArrayB, "\nA+B: ",output)
    
    randArrayX = np.random.rand(1024, 1024)
    print("\nX:", randArrayX, "\nX*X:", aSession.run(yNode, feed_dict={xNode: randArrayX}))  # Will succeed.
aSession.close()

A:  [[0.87102941 0.8044195 ]] 
B:  [[0.43596265 0.18756064]] 
A+B:  [[1.306992  0.9919802]]

X: [[0.68873025 0.70586041 0.33634668 ... 0.89002756 0.53578776 0.40702574]
 [0.92456983 0.99341682 0.04845532 ... 0.27990118 0.9743113  0.7921947 ]
 [0.93033919 0.31557995 0.52875053 ... 0.54725981 0.11413419 0.80530257]
 ...
 [0.17897704 0.20638099 0.93131107 ... 0.37932413 0.26623807 0.61323282]
 [0.70097532 0.8168579  0.18886742 ... 0.43863398 0.65556969 0.81344977]
 [0.63265126 0.22231365 0.24139989 ... 0.69689983 0.68965193 0.70598646]] 
X*X: [[268.01447 255.37022 265.48386 ... 260.77008 256.93347 264.95584]
 [262.37158 248.21074 258.25925 ... 252.96368 250.4609  254.59473]
 [263.54474 246.0625  256.24838 ... 257.88358 254.6499  256.80545]
 ...
 [266.49362 254.3628  265.47583 ... 261.80026 258.68918 264.70462]
 [257.20786 241.20898 254.83875 ... 248.1103  254.61093 255.64911]
 [256.97766 241.38652 251.75496 ... 246.01385 243.98114 249.55927]]


<br>
**3. Variables**: Used to integrate trainable parameters to the graph. The weights and the offset are the best examples of variables. Here is an example of variable usage in training a model:-

In [83]:
# Model parameters
W = tf.Variable([.30], tf.float32)
b = tf.Variable([-.30], tf.float32)

# input and output variables
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

linearModel = W*x + b

# Loss (this will tell us how far we are from getting to the right answer)
squaredDelta = tf.square(linearModel - y)
loss = tf.reduce_sum(squaredDelta)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

# Initialize all the variables
init = tf.global_variables_initializer()

'''
An Optimizer modifies each variable according to the magnitude of the derivate of the
loss with respect to that variable. Gradient Descent is a type of Optimizer.

Gradient Descent:-

Suppose there is a Hiker are on the top of a mountain in a mountain range. The Hiker is blindfolded and
he wants to reach the ground. He starts moving in the direction that takes him lower until it starts
going up again.

Hence, the Position of hiker is weight. Length of the step is the learning rate.

OR in other words:

An Optimizer will calculate the change in the loss WRT to change in the variable. If the loss is 
decreasing then it will continue changing the varibale in that direction.
'''

with tf.Session() as someSession:
    someSession.run(init)

    for i in range(1000):
        someSession.run(train, {x:[1,2,3,4], y:[0,-1,-2,-3]})
    print (someSession.run([W, b]))
someSession.close()

[array([-0.9999969], dtype=float32), array([0.9999908], dtype=float32)]


**Creating a classifier using what we have learned/used so far**

Problem: (Binary Classificatoin) Given some training data with n features and corresponding labels (0 or 1), train a binary classifier and predict the labels on the test set.

In [170]:
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

def readData():
    # Read the training data and separate the dependent variable from the features
    trainDataFrame = pd.read_csv("train.csv")
    nCols = len(trainDataFrame.columns)
    X = trainDataFrame[trainDataFrame.columns[0:nCols-1]].values
    y = trainDataFrame[trainDataFrame.columns[nCols-1]].values
    
    # Encoding the dependent variable
    # Incase of labels such as "Yes" and "No", we want to map them to a corresponding label vector
    # that has all zeroes expect at the corresponding label.
    encoder = LabelEncoder()
    encoder.fit(y)
    y = encoder.transform(y)
    Y = one_hot_encode(y)
    
    return (X, Y)
    
def one_hot_encode(labels):
    nLabels = len(labels)
    nUniqueLabels = len(np.unique(labels))
    one_hot_encode = np.zeros((nLabels, nUniqueLabels))
    one_hot_encode[np.arange(nLabels), labels] = 1
    return one_hot_encode
    
    
X, Y = readData()
X, Y = shuffle(X, Y, random_state=1)

# Dividing the training data into train and dev sets
train_x, test_x, train_y, test_y = train_test_split(X, Y, test_size = 0.2, random_state = 415)

# Inspect the shape after dividing into the right data sets
# print ((train_x.shape))
# print ((test_x.shape))
# print ((train_y.shape))
# print ((test_y.shape))

# Important parameters and modelling variables
learning_rate = 0.25
training_epochs = 1000
cost_history = np.empty(shape=[1], dtype=float)

# dimension of the feature vector
n_dim = X.shape[1]
# Number of possible labels / output classes
n_class = Y.shape[1]

# Define the number of hidden layers and Neurons in each layer
n_hidden_1 = 40
n_hidden_2 = 40
n_hidden_3 = 40
n_hidden_4 = 40

# input and output variables
x = tf.placeholder(tf.float32, [None, n_dim]) # None tells that it can be any value
W = tf.Variable(tf.zeros([n_dim,n_class]))
b = tf.Variable(tf.zeros([n_class]))
y = tf.placeholder(tf.float32, [None, n_class]) # None tells that it can be any value

# Defining the model
def multiLayerPerceptron(x, weights, biases):
    
    layer_1 = tf.add(tf.matmul(x, weights["h1"], biases["b1"]))
    layer_1 = tf.nn.sigmoid(layer_1)
    
    layer_2 = tf.add(tf.matmul(layer_1, weights["h2"], biases["b2"]))
    layer_2 = tf.nn.sigmoid(layer_2)

    layer_3 = tf.add(tf.matmul(layer_2, weights["h3"], biases["b3"]))
    layer_3 = tf.nn.sigmoid(layer_3)

    layer_4 = tf.add(tf.matmul(layer_3, weights["h4"], biases["b4"]))
    layer_4 = tf.nn.relu(layer_4)
    
    layer_out = tf.matmul(layer_4, weights["out"], biases["out"])
    
    return layer_out

weights = {
    'h1': tf.Variable(tf.truncated_normal([n_dim, n_hidden_1])),
    'h2': tf.Variable(tf.truncated_normal([n_hidden_1, n_hidden_2])),
    'h3': tf.Variable(tf.truncated_normal([n_hidden_2, n_hidden_3])),
    "h4": tf.Variable(tf.truncated_normal([n_hidden_3, n_hidden_4])),
    "out": tf.Variable(tf.truncated_normal([n_hidden_4, n_class]))
}

biases = {
    'b1': tf.Variable(tf.truncated_normal([n_hidden_1])),
    'b2': tf.Variable(tf.truncated_normal([n_hidden_2])),
    'b3': tf.Variable(tf.truncated_normal([n_hidden_3])),
    "b4": tf.Variable(tf.truncated_normal([n_hidden_4])),
    "out": tf.Variable(tf.truncated_normal([n_class]))
}